[package]
name = "whitespace-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.3"
utf8-decode = "^1.0"

[dev-dependencies]
tempfile = "^3.2"
